### PR TITLE
Update to add aggregates and remove case sensitivity

### PR DESCRIPTION
**Pull request by glyphstalker**
Updated the Select Case statement to allow the input string to be any case, added aggregates for "First", "Last", and "CountDistinct", and refactored the internal methodology into separate functions so as to not perform operations that do not contribute to the aggregation specified.

### CODE REVIEW

**Review by stephlocke — CHANGES_REQUESTED** [review]
Code looks great. Teeny weeny thing - could you remove the "self explanatory" strings in the comments - either what's there isn't good enough for someone to understand and you'll make them feel bad or if it's sufficient it's redundant. 

Thank you so much for this PR :D

**Comment by glyphstalker** [comment]
I removed the comments that were tagged as 'Self Explanatory' and reduced some redundancy.  Also fixed a typo in the comment at line  13.  

I appreciate the positive feedback; this is my first pull request, so not 100% familiar with the expectations, but I wanted to contribute to this one because it looked like it could benefit from what I had added for my project.

I'm unsure if I need to submit the pull request again after committing the changes or if they are available to you already.  Also, I am not opposed to making any other changes you feel should be there; This was your repository to begin with, I am trying to keep it in line with what you had already.

Thank you again for your feedback, it is much appreciated.

**Review by stephlocke — APPROVED** [review]

**Comment by stephlocke** [comment]
@glyphstalker you did a great job :D 

Thanks so much for amending this! We don't get the chance to do much SSRS these days so someone else helping improve this takes a load off my mind.

**Comment by glyphstalker** [comment]
You're very welcome, I was glad to do it; SSRS doesn't seem to change too much, so hopefully this will continue to serve as a self contained solution moving forward (at least as far as aggregates on lookupsets). 

I tested it side by side with your original method, so all inputs and outputs should be compatible.  Hopefully, if someone wanted to, they could move to this without any changes other than dropping in the revised code. 

Also, I wanted to thank you for providing this in the first place.  I honestly hadn't even realized the ReportBuilder allowed you to drop in code until I saw what you were doing.  Also, your implementation was very well explained, which allowed me to adjust it very easily without worry that I was changing the intent of a specific method.

Thank you again :)

**Pull request merged**
